framework:
  messenger:
    serializer:
      default_serializer: Framework\IntegratedService\Messenger\Service\LazyServiceSerializer
      symfony_serializer:
        format: json
        context: { }
